# Change these first
owner: taoky # Your GitHub username
repo: sites-status # Your Github repository name

# Add your sites here
sites:
  - name: USTC
    url: https://www.ustc.edu.cn
  - name: Homepage
    url: https://taoky.moe
  - name: Static files of taoky.moe
    url: https://static.taoky.moe
  - name: USTCLUG
    url: https://lug.ustc.edu.cn
  - name: USTC Mirrors
    url: https://mirrors.ustc.edu.cn
  - name: LUG GitLab
    url: https://git.lug.ustc.edu.cn
  - name: LUG FTP
    url: https://ftp.lug.ustc.edu.cn
  - name: proxy.ustclug.org
    url: https://openwrt.proxy.ustclug.org

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.taoky.moe
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
